#cloud-config
hostname: "firewall-template"

users:
  - name: admin
    gecos: "Admin User"
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/sh
    lock-passwd: false
    passwd: "$6$b9T6gEnQwVvxM5gV$MIecEzUmOUeJFs4Z/BCKDcbowu0s/0qgVFqLoL3ZEYs18ik6JFBsBXZsXKiu.UuLEKd9VlttjkUh/XSpj90d6/"  # Password --> opnsense

# cloud-init configuration pour FreeBSD avec installation d'OPNsense
runcmd:
  # Configuration réseau manuelle pour vtnet0
  - "echo 'ifconfig_vtnet0=\"inet 192.168.1.141 netmask 255.255.255.0\"' >> /etc/rc.conf"
  - "echo 'defaultrouter=\"192.168.1.254\"' >> /etc/rc.conf"
  - "echo 'nameserver 192.168.1.254' > /etc/resolv.conf"

  # Redémarrer les services réseau pour appliquer les changements de configuration
  - "service netif restart"
  - "service routing restart"
  
  # Vérification de la connectivité réseau
  - "ping -c 3 google.com"
  - "sleep 10"  # Attendre 10 secondes pour s'assurer que le réseau fonctionne correctement
  
  # Mettre à jour les paquets avec un miroir alternatif
  #- "sed -i '' 's/pkg.FreeBSD.org/pkg.freebsd.org/g' /etc/pkg/FreeBSD.conf"
  - "pkg update -f"
  - "sleep 10"  # Attendre 10 secondes pour permettre à pkg de se mettre à jour
  
  # Télécharger le script d'installation OPNsense
  #- "fetch https://raw.githubusercontent.com/opnsense/update/master/src/bootstrap/opnsense-bootstrap.sh.in"
  - "fetch https://raw.githubusercontent.com/opnsense/update/master/src/bootstrap/opnsense-bootstrap.sh.in -o /tmp/opnsense-bootstrap.sh.in"
  - "sleep 10"  # Attendre 10 secondes pour que le fichier soit téléchargé
  
  # Vérifier que le fichier a bien été téléchargé
  - "ls -l /tmp/opnsense-bootstrap.sh.in"
  
  # Rendre le script exécutable
  - "chmod +x /tmp/opnsense-bootstrap.sh.in"
  # Vérifier que le fichier a bien été téléchargé
  - "ls -l /tmp/opnsense-bootstrap.sh.in"
  
  - "sleep 10"  # Attendre quelques secondes pour rendre le fichier exécutable
  
  # Exécuter le script d'installation d'OPNsense
  - "sh /tmp/opnsense-bootstrap.sh.in -r 25.1"
  - "sleep 10"  # Attendre un peu avant de redémarrer pour permettre à OPNsense de s'installer
  
  # Redémarrer le système pour appliquer les changements et démarrer OPNsense
  #- "reboot"
