#cloud-config
hostname: "firewall-interne"
write_files:
  - path: /etc/rc.conf
    content: |
      # Interfaces configuration
      ifconfig_vtnet0="inet 172.16.30.1 netmask 255.255.255.0" # WAN (vmbr0)
      ifconfig_vtnet1="inet 172.16.1.8 netmask 255.255.255.0" # LAN (vmbr1)
      
      # VLAN Configuration (OPT1)
      vlan5="vlan 5 vlandev vtnet2"
      ifconfig_vlan5="inet 172.16.5.254 netmask 255.255.255.0" # VLAN 5 (OPT1 vmbr4)
      
      vlan10="vlan 10 vlandev vtnet2"
      ifconfig_vlan10="inet 172.16.10.254 netmask 255.255.255.0" # VLAN 10 (OPT1 vmbr4)
      
      vlan20="vlan 20 vlandev vtnet2"
      ifconfig_vlan20="inet 172.16.20.14 netmask 255.255.255.240" # VLAN 20 (OPT1 vmbr4)

      # Enable NAT
      gateway_enable="YES"
      pf_enable="YES"
      echo "nat on vtnet0 from 172.16.1.0/24 to any -> (vtnet0)" >> /etc/pf.conf
      echo "nat on vtnet0 from 172.16.5.0/24 to any -> (vtnet0)" >> /etc/pf.conf
      echo "nat on vtnet0 from 172.16.10.0/24 to any -> (vtnet0)" >> /etc/pf.conf
      echo "nat on vtnet0 from 172.16.20.0/28 to any -> (vtnet0)" >> /etc/pf.conf

      # Firewall rules
      echo "pass in on vtnet1 from 172.16.1.0/24 to any" >> /etc/pf.conf
      echo "pass in on vlan5 from 172.16.5.0/24 to any" >> /etc/pf.conf
      echo "pass in on vlan10 from 172.16.10.0/24 to any" >> /etc/pf.conf
      echo "pass in on vlan20 from 172.16.20.0/28 to any" >> /etc/pf.conf

      # Routes
      echo "route add -net 172.16.30.0/28 172.16.5.254" >> /etc/rc.conf
      echo "route add -net 172.16.40.0/27 172.16.5.254" >> /etc/rc.conf
      echo "route add -net 172.16.50.0/28 172.16.5.254" >> /etc/rc.conf

  - path: /etc/sysctl.conf
    content: |
      net.inet.ip.forwarding=1

runcmd:
  # Mettre à jour les paquets
  - "pkg update -f"
  
  # Ajouter le dépôt d'OPNsense
  - "echo 'OPNsense repository configuration' >> /usr/local/etc/pkg/repos/OPNsense.conf"
  - "echo 'OPNsense: { url: \"http://pkg.opnsense.org/freebsd/$(uname -r)/amd64/latest\", enabled: yes }' >> /usr/local/etc/pkg/repos/OPNsense.conf"

  # Installer OPNsense depuis le dépôt officiel
  - "pkg install -y opnsense"

  # Activer le pare-feu et démarrer le service
  - "sysrc firewall_enable=YES"
  - "sysrc pf_enable=YES"
  - "service pf start"

  # Redémarrer pour appliquer les changements
  - "reboot"
